#!/bin/sh

## This script is used to run the scala implementation of the
## solo Tru'ng AI for Fire in the Lake

## Set the current working directory to the directory where this script is running.
## This is important so that all of our relative path references work correctly.
cd `dirname $0`

CLASSPATH=lib/fire-in-the-lake_2.12-0.1.jar:lib/optparse_2.12-2.2.jar:lib/scala-library-2.12.15.jar:\
lib/scala-parser-combinators_2.12-1.1.2.jar:lib/scala-reflect-2.12.15.jar:lib/scalactic_2.12-3.0.1.jar

java -cp "$CLASSPATH"  fitl.FireInTheLake "$@"
