#!/bin/sh
##  _____ _            _         _   _            _          _
## |  ___(_)_ __ ___  (_)_ __   | |_| |__   ___  | |    __ _| | _____
## | |_  | | '__/ _ \ | | '_ \  | __| '_ \ / _ \ | |   / _` | |/ / _ \
## |  _| | | | |  __/ | | | | | | |_| | | |  __/ | |__| (_| |   <  __/
## |_|   |_|_|  \___| |_|_| |_|  \__|_| |_|\___| |_____\__,_|_|\_\___|
##
##
## This script is used to run the scala implementation of the
## solo Tru'ng AI for Fire in the Lake

## Set the current working directory to the directory where this script is running.
## This is important so that we can find the jar files in the lib subdirectory.
cd `dirname $0`

java -cp "lib/loader.jar" -D"loader.targetClass=fitl.FireInTheLake" loader.Loader "$@"
