#!/bin/sh

## This script is used to run the scala implementation of the
## solo Tru'ng AI for Fire in the Lake

## Set the current working directory to the directory where this script is running.
## This is important so that all of our relative path references work correctly.
cd `dirname $0`

CLASSPATH=lib/fire-in-the-lake_2.13-1.0.jar:\
lib/scala-library-2.13.10.jar:\
lib/scala-parser-combinators_2.13-2.1.1.jar

java -cp "$CLASSPATH"  fitl.FireInTheLake "$@"
